[main]
environment = production

[master]
ssl_client_header = SSL_CLIENT_S_DN
ssl_client_verify_header = SSL_CLIENT_VERIFY
certname = ubuntu-devops
report = true
reports = log

[agent]
server = ubuntu-devops
certname = ubuntu-devops
pluginsync = true
report     = true
summarize  = true
runinterval = 30m
report = true